from cmath import exp
from unittest import expectedFailure
from dateOP import currentTime


currentTime()


def additoin(x, y):
        x = 10
        y = 20
        print("Addition:", x + b)


additoin(10, 20)

while True:
    try:
        print("the operation is successful")
        break
    except Exception as e:
        print(e)
    

